const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {parseFilters,buildReport,loadReport}=require('../src/reports/reportData');
const {workbook,excelDate,crc32,xml}=require('../src/reports/reportWorkbook');
const env='111111111111111111111111',off='222222222222222222222222',cash='333333333333333333333333',wallet='444444444444444444444444',p1='555555555555555555555555',p2='666666666666666666666666';
const users=[{id:off,fullName:'קצין בדיקה',personalNumber:'000123'},{id:cash,fullName:'מנהל בדיקה'}],wallets=[{id:wallet,name:'ארנק בדיקה',walletNumber:'0009'}];
const items=[{productId:p1,productName:'מחברת',categoryName:'כתיבה',quantity:2,unitPrice:5,lineTotal:10},{productId:p2,productName:'עט',categoryName:'כתיבה',quantity:1,unitPrice:20,lineTotal:20}];
const base={id:'a',transactionNumber:'T1',createdAt:new Date('2026-09-15T10:00:00Z'),officerId:off,cashierId:cash,walletId:wallet,totalAmount:30,transactionType:'sale',status:'completed',items,environmentId:env};
const tx=[base,{...base,id:'b',transactionNumber:'T2',transactionType:'return',totalAmount:5,items:[{...items[0],quantity:1,lineTotal:5}]},{...base,id:'c',transactionNumber:'T3',transactionType:'deposit',officerId:cash,totalAmount:100,items:[]},{...base,id:'d',transactionNumber:'T4',transactionType:'withdrawal',officerId:cash,totalAmount:7,items:[]}];
const filt=q=>parseFilters({from:'2026-09-01T00:00:00Z',to:'2026-09-17T00:00:00Z',...q});
const report=q=>({mode:q?.mode||'transactions',environment:{id:env,name:'סביבת בדיקה'},generatedAt:new Date('2026-09-16T10:00:00Z'),filters:filt(q),...buildReport(tx,users,wallets,filt(q))});
test('deposits excluded from net sales',()=>{const r=report();assert.equal(r.summary.netSales,25);assert.equal(r.summary.deposits,100);assert.equal(r.summary.walletMovement,68);});
test('no multiplication of transaction totals by number of lines',()=>{const r=report();assert.equal(r.summary.sales,30);assert.equal(r.rows.length,4);assert.equal(r.lines.length,3);assert.equal(r.groups.officers[0].transactions,2);});
test('line filtering has separate matched and whole amounts',()=>{const r=report({productIds:JSON.stringify([p1])});assert.equal(r.summary.sales,10);assert.equal(r.rows[0].totalAmount,30);assert.equal(r.rows[0].matchedAmount,10);assert.equal(r.lines.length,2);});
test('officer filter never treats a deposit as products taken',()=>{assert.equal(report({officerIds:off}).rows.length,2);assert.equal(report({officerIds:cash}).rows.length,0);});
test('officer history is not inferred from current wallet owners',()=>{assert.equal(report().rows[0].officerName,'קצין בדיקה');assert.match(report().rows[0].receiverEvidence,/רישום ישן/);});
test('confirmed receiver marker shown only when present',()=>{const r=buildReport([{...base,officerSelectionConfirmed:true}],users,wallets,filt());assert.match(r.rows[0].receiverEvidence,/שאושרה/);});
test('missing balance snapshots remain unknown',()=>{const r=report();assert.equal(r.rows[0].walletBalanceBefore,null);assert.equal(r.rows[0].walletBalanceAfter,null);});
test('recorded snapshots preserved',()=>{const r=buildReport([{...tx[2],walletBalanceBefore:20,walletBalanceAfter:120}],users,wallets,filt());assert.equal(r.rows[0].walletBalanceAfter,120);});
test('inactive historical users still appear via observed IDs',()=>assert.ok(report().options.officers.some(o=>o.id===off)));
test('name and personal-number search',()=>{assert.equal(report({q:'000123'}).rows.length,2);assert.equal(report({q:'ארנק בדיקה'}).rows.length,4);});
test('cashier selection',()=>assert.equal(report({cashierIds:cash,types:'sale'}).rows.length,1));
test('credits mode shows only money movements',()=>{const r=report({mode:'credits'});assert.equal(r.rows.length,2);assert.equal(r.summary.netSales,0);});
test('products mode excludes deposits',()=>assert.equal(report({mode:'products'}).rows.length,2));
test('cancelled transactions excluded from monetary totals',()=>{const r=buildReport([{...base,status:'cancelled'}],users,wallets,filt({status:'all'}));assert.equal(r.rows.length,1);assert.equal(r.summary.netSales,0);});
test('no data is not a failed report',()=>assert.equal(buildReport([],[],[],filt()).summary.transactions,0));
test('category containing comma can be filtered',()=>assert.deepEqual(filt({categories:'["שם, נוסף"]'}).categories,['שם, נוסף']));
for(const q of [{from:'bad'},{from:'2027-01-01',to:'2026-01-01'},{from:'2020-01-01',to:'2026-01-01'},{mode:'private'},{status:'bad'},{min:'1.001'},{min:'2',max:'1'},{walletIds:'not-an-id'},{types:'unknown'},{categories:'[1]'},{categories:'['},{q:'a'.repeat(121)}])test('reject invalid filters '+JSON.stringify(q),()=>assert.throws(()=>filt(q),{status:400}));
test('date query and all tenant lookups are scoped',async()=>{
 let where,readIds;const tenant={transaction:{findMany:async a=>{where=a.where;assert.equal(a.take,5001);return tx;}},wallet:{findMany:async a=>{assert.equal(a.where.environmentId,env);return wallets;}}};
 const people={user:{findMany:async a=>{readIds=a.where.id.in;return users;}}};
 await loadReport(tenant,people,{id:env,name:'test'},{from:'2026-09-01T00:00:00Z',to:'2026-09-17T00:00:00Z'});assert.equal(where.environmentId,env);assert.equal(where.createdAt.lt.toISOString(),'2026-09-17T00:00:00.000Z');assert.deepEqual(readIds.sort(),[off,cash].sort());
});
test('large report rejects instead of silently truncating',async()=>{await assert.rejects(loadReport({transaction:{findMany:async()=>Array(5001).fill(base)}},{},{id:env},{}),{status:422});});
test('inventory missing costs not treated as known zero costs',async()=>{const tenant={product:{findMany:async a=>{assert.equal(a.where.environmentId,env);return [{id:p1,name:'a',quantity:3,costPerUnit:null},{id:p2,name:'b',quantity:2,costPerUnit:5}];}}};const r=await loadReport(tenant,{},{id:env},{mode:'inventory'});assert.equal(r.summary.knownInventoryValue,10);assert.equal(r.summary.missingCosts,1);});
function accessHarness(user,options={}){let tenantCreated=0;const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/reports/reportAccess.js'),'utf8'),{module,process:{env:{JWT_SECRET:'test-only'}},require(name){if(name==='jsonwebtoken')return{verify(){if(options.invalidToken)throw Error('invalid');return{id:user.id,...options.claims};}};if(name.includes('database'))return{usersPrisma:{user:{findUnique:async()=>user},userEnvironment:{findUnique:async()=>options.noMember?null:{role:user.role}}},controlPrisma:{environment:{findUnique:async()=>({id:env,name:'test',dbName:'test-only',isActive:true})}},getTenantPrismaByDbName(){tenantCreated++;return{};}};throw Error(name);}});return async(query={environmentId:env})=>{let status=200,nexted=false;await module.exports.reportAccess({headers:{authorization:'Bearer token','x-user-id':user.id},query},{set(){},status(n){status=n;return this;},json(){return this;}},e=>{if(e)throw e;nexted=true;});return{status,nexted,tenantCreated};};}
for(const role of ['admin','superadmin'])test('report access allows '+role,async()=>assert.equal((await accessHarness({id:cash,role,isActive:true,environmentId:env})()).nexted,true));
for(const role of ['officer','cashier'])test('report access denies '+role,async()=>assert.equal((await accessHarness({id:cash,role,isActive:true,environmentId:env})()).status,403));
test('report access denies stale environment',async()=>assert.equal((await accessHarness({id:cash,role:'admin',isActive:true,environmentId:env})({environmentId:off})).status,409));
test('report access requires selected scope',async()=>assert.equal((await accessHarness({id:cash,role:'superadmin',isActive:true,environmentId:null})()).status,400));
test('report access rejects failed signature boundary before tenant lookup',async()=>{const r=await accessHarness({id:cash,role:'admin',isActive:true,environmentId:env},{invalidToken:true})();assert.equal(r.status,401);assert.equal(r.tenantCreated,0);});
test('report access denies missing membership',async()=>assert.equal((await accessHarness({id:cash,role:'admin',isActive:true,environmentId:env},{noMember:true})()).status,403));
test('report access never imports tenant bootstrap',()=>assert.doesNotMatch(fs.readFileSync(path.join(__dirname,'../src/reports/reportAccess.js'),'utf8'),/bootstrapTenantEnvironment|ensureEnvironmentDbName|authenticateToken/));
test('OOXML escaping preserves text safely',()=>assert.equal(xml('=1+1<&\u0000'),'=1+1&lt;&amp;'));
test('Excel time is converted to Israel local wall time',()=>assert.equal(excelDate('2026-09-16T09:00:00Z'),(Date.UTC(2026,8,16,12)-Date.UTC(1899,11,30))/86400000));
test('ZIP crc known vector',()=>assert.equal(crc32(Buffer.from('123456789')),0xcbf43926));
test('XLSX is a real ZIP, not CSV renamed',()=>assert.equal(workbook(report()).readUInt32LE(0),0x04034b50));
